### ISSUE TITLE
update run_Wochenende_SLURM.sh

### ISSUE THREAD

**Issue by colindaven** [sannareddyk/metagenome_mgsammlung#12]
Hi Keerthi,

it looks like you still have to update `run_Wochenende_SLURM.sh` to have the example uses for the new Nextera functionality.

Also, the later Wochenende version is 1.7.1.
run_Wochenende.py

Both should be available here: 
https://github.com/MHH-RCUG/Wochenende

cheers,
Colin

**Comment by sannareddyk** [comment]
Hi @colindaven ,
Updated run_Wochenende_SLURM.sh and run_Wochenende.py scripts.
Please feel free to test the harz pipeline.
Thanks,
Keerthi
