### ISSUE TITLE
Program commands ok, but no binaries

### ISSUE THREAD

**Issue by colindaven** [sannareddyk/metagenome_mgsammlung#2]
We should not store binary files here:

[3:29 PM] Colin Davenport
    I guess we have to be careful we don't add anyone else's programs (code) to this, if this might break licenses. 
​[3:29 PM] Colin Davenport
    Just config/run commands should be fine though

**Comment by colindaven** [comment]
Use git submodules ? Or conda

**Comment by sannareddyk** [comment]
using conda environments to run the programs
