### ISSUE TITLE
main method and functions

### ISSUE THREAD

**Issue by colindaven** [sannareddyk/metagenome_mgsammlung#7]
Hi Keerthi,

it would be great to divide up the code into methods/functions to enable readability and good programming practice, especially as the tool gets more complex.

Thanks,
Colin

**Comment by sannareddyk** [comment]
Hi Colin,
I have restructured the code and have added different tools as functions, and also added a main method. At the moment the code works with *.fastq files and runs Wochenende and Krakenuniq pipelines. I have to work on thread.join() methods, to execute cleanup.sh and other scripts once the pipeline functions complete running/terminate.
